# Generated by Django 4.1 on 2023-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_Publication_date', models.DateField(verbose_name='Ref.Publication date')),
                ('DOI', models.CharField(max_length=32, verbose_name='DOI')),
                ('img', models.FileField(max_length=128, upload_to='main/', verbose_name='Logo')),
            ],
        ),
    ]
