# Generated by Django 4.1 on 2023-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='Efficiency_Current_modified_l',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='TENG_Improve_friction_properties_or_propose_new_methods',
        ),
        migrations.AddField(
            model_name='essay',
            name='Efficiency_Charge_nC',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Efficiency.Charge(nC)'),
        ),
        migrations.AddField(
            model_name='essay',
            name='Efficiency_Current_nA',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Efficiency.Current modified(nA)'),
        ),
        migrations.AddField(
            model_name='essay',
            name='Ref_Publication_date_digit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Ref.Publication date(Digit)'),
        ),
        migrations.AddField(
            model_name='essay',
            name='Structure',
            field=models.SmallIntegerField(choices=[(1, 'Spring'), (2, 'Sandwich'), (3, 'Roll'), (4, 'Rotation'), (5, 'Line'), (6, 'Gear'), (7, 'Ratchet'), (8, 'Rod'), (9, 'Bearing'), (10, 'Beam'), (11, 'Folding'), (12, 'Wind'), (13, 'Origami'), (14, 'Softness'), (15, 'Textile'), (16, 'Nothing')], default=1, verbose_name='Specific structure'),
        ),
        migrations.AddField(
            model_name='essay',
            name='TENG_MFCFP',
            field=models.SmallIntegerField(choices=[(1, 'ICP'), (2, 'Light'), (3, 'Film coating'), (4, 'Textile fiber'), (5, 'Chemical etch'), (6, 'Gel'), (7, 'Mosaic particle'), (8, 'Electrospinning'), (9, '3D printing'), (10, 'Nothing')], default=1, verbose_name='TENG.MFCFP'),
        ),
        migrations.AddField(
            model_name='essay',
            name='TENG_Mode',
            field=models.SmallIntegerField(choices=[(1, 'TM'), (2, 'DC'), (3, 'SL')], default=1, verbose_name='TENG.Mode'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Efficiency_Charge',
            field=models.CharField(max_length=64, verbose_name='Efficiency.Charge(Input)'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Efficiency_Current',
            field=models.CharField(max_length=64, verbose_name='Efficiency.Current(Input)'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Efficiency_Current_modified',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Efficiency.Current modified(μA/cm2)'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Efficiency_Power',
            field=models.CharField(max_length=64, verbose_name='Efficiency.Power(Input)'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Level',
            field=models.SmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Mode',
            field=models.SmallIntegerField(choices=[(1, 'Contact separation'), (2, 'Horizontal slide'), (3, 'Single electrode'), (4, 'Independent layer'), (5, 'Phase coupling'), (6, 'Dielectric breakdown'), (7, 'Electric brush'), (8, 'Ternary Dielectric Triboelectrification Effect'), (9, 'Semiconductor'), (10, 'Single'), (11, 'Contact'), (12, 'Non-Contact'), (13, 'Semiconductor-Metal')], default=1, verbose_name='Specific mode'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Ref_Publication_date',
            field=models.DateField(verbose_name='Ref.Publication date[year:mm:dd]'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='TENG_structure',
            field=models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Machine'), (3, 'IMTRM'), (4, 'Nothing')], default=1, verbose_name='TENG.structure'),
        ),
    ]
