# Generated by Django 4.1 on 2023-05-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_remove_essay_efficiency_current_modified_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='Structure',
            field=models.SmallIntegerField(choices=[(1, 'Spring'), (2, 'Sandwich'), (3, 'Roll'), (4, 'Rotation'), (5, 'Line'), (6, 'Gear'), (7, 'Ratchet'), (8, 'Rod'), (9, 'Bearing'), (10, 'Beam'), (11, 'Folding'), (12, 'Wind'), (13, 'Origami'), (14, 'Softness'), (15, 'Textile'), (16, 'Water droplet'), (17, 'Nothing')], default=1, verbose_name='Specific structure'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='TENG_MFCFP',
            field=models.CharField(max_length=64, verbose_name='TENG.MFCFP'),
        ),
    ]
