# Generated by Django 4.1 on 2023-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0004_alter_essay_structure_alter_essay_teng_mfcfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_Publication_date', models.DateField(verbose_name='Ref.Publication date')),
                ('DOI', models.CharField(max_length=64, verbose_name='DOI')),
                ('img', models.FileField(max_length=128, upload_to='sl/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='essay',
            name='Mode_Get_electrons_layer',
            field=models.CharField(max_length=255, verbose_name='Mode.Get electrons layer'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Mode_Get_electrons_layer_Electrode_layer',
            field=models.CharField(max_length=255, verbose_name='Mode.Get electrons layer.Electrode layer'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Mode_Loss_electrons_Electrode_layer',
            field=models.CharField(max_length=255, verbose_name='Mode.Loss electrons.Electrode layer'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Mode_Loss_electrons_layer',
            field=models.CharField(max_length=255, verbose_name='Mode.Loss electrons layer'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='Ref_Article_title',
            field=models.CharField(max_length=255, verbose_name='Ref.Article title'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='TENG_MFCFP',
            field=models.CharField(max_length=255, verbose_name='TENG.MFCFP'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='TENG_Power_generation_application',
            field=models.CharField(max_length=255, verbose_name='TENG.Power generation.application'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='TENG_Sensor_field_application',
            field=models.CharField(max_length=255, verbose_name='TENG.Sensor field.application'),
        ),
        migrations.AlterField(
            model_name='main',
            name='DOI',
            field=models.CharField(max_length=64, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='main',
            name='img',
            field=models.FileField(max_length=128, upload_to='main/', verbose_name='Image'),
        ),
    ]
